" wget https://raw.githubusercontent.com/gbxu/EnvDeployment/main/.vimrc
" General
set number	" Show line numbers 行号
set linebreak	" Break lines at word (requires Wrap lines) 换行
set showbreak=+++	" Wrap-broken line prefix
set textwidth=100	" Line wrap (number of cols) 行宽
set showmatch	" Highlight matching brace 括号匹配高亮
set visualbell	" Use visual bell (no beeping) 屏幕闪烁代替声音
" 搜索高亮+自动大小写
set hlsearch	" Highlight all search results 
set smartcase	" Enable smart-case search 
set ignorecase	" Always case-insensitive 
set incsearch	" Searches for strings incrementally
"  自动缩进
set autoindent	" Auto-indent new lines
set expandtab	" Use spaces instead of tabs
set shiftwidth=4	" Number of auto-indent spaces
set smartindent	" Enable smart-indent
set smarttab	" Enable smart-tabs
set softtabstop=4	" Number of spaces per Tab
 
" Advanced
set ruler	" Show row and column ruler information
 
set undolevels=1000	" Number of undo levels
set backspace=indent,eol,start	" Backspace behaviour
 
 
" Generated by VimConfig.com

" Others
set paste " 粘贴保持原格式
set encoding=utf-8
set mouse=a " 支持鼠标
set cursorline " highlight current line 高亮当前行
set showmode " 状态量显示模式
syntax enable " colorful syntax 语法高亮


set viminfo='10,\"100,:20,%,n~/.viminfo
au BufReadPost * if line("'\"") > 0|if line("'\"") <= line("$")|exe("norm '\"")|else|exe "norm $"|endif|endif
